In [2]:
# Syntax open: open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)
# mode: r (read), w (write), a (append)
f = open('agencies.txt', 'r')
# read all the content to a list
lines = f.readlines()
for li in lines:
    print(li.strip())

f.close()

Federal Bureau of Investigation
Central Intelligence Agency
The Triboro Bridge and Tunnel Authority
Housing and Urban Development
The Metropolitan Transit Authority
The Port Authority of New York and New Jersey


In [23]:
f = open('agencies.txt', 'r')
fw = open('agencies_authority.txt', 'w')
# read content line by line
for line in f:
    if 'authority' in line.lower():
        print(line.strip())
        fw.write(line)
f.close()
fw.close()

The Triboro Bridge and Tunnel Authority
The Metropolitan Transit Authority
The Port Authority of New York and New Jersey


In [ ]:
# Read authors.txt, print name & email
f = open('authors.txt', 'r')
# Skip 3 first lines
for _ in range(3):
    next(f)
# TODO: split line to get name & email
for line in f:
    name, email = line.split('<')
    name = name.strip() + ':'
    email = email.strip()[:-1]
    print(f'{name:25}{email:25}')

f.close()

In [12]:
import numpy as np
data = np.loadtxt('falling.txt', skiprows=5)
print(data)

[[  0.    0.  180.    3.5]
 [  1.    0.5 185.    4.5]
 [  2.    0.7 192.    5.2]]


In [13]:
times = data[:, 1]
print(times)
heights = data[:, 2]
print(heights)

[0.  0.5 0.7]
[180. 185. 192.]


In [14]:
times, heights = np.loadtxt('falling.txt', skiprows=5, usecols=(1, 2), unpack=True)
print(times)
print(heights)

[0.  0.5 0.7]
[180. 185. 192.]


In [25]:
student_data = np.loadtxt('gradebook.csv', delimiter=',', skiprows=1, dtype=str)
# Clean student data
for student in student_data:
    if student[4] == '':
        student[4] = '0'
    if float(student[4]) > 10:
        student[4] = '10'
    if student[2] == '':
        student[2] = 'GCH22000'
# Print student data
# for student in student_data:
#     if float(student[4]) >= 6.5:
#         print(f'{student[2]:10}{student[3]:20}{student[4]:10}')
pass_students = [['Login','Email','Code','Name','Grade']]
pass_students += [student for student in student_data if float(student[4]) >= 6.5]
for st in pass_students:
    print(f'{st[2]:10}{st[3]:20}{st[4]:10}')

# Write to file
np.savetxt('pass_students.csv', pass_students, delimiter=',', fmt='%s')

Code      Name                Grade     
GBH17538  Le Minh Huong       6.5       
GCH16336  Nguyen The Dat      6.5       
GCH16388  Pham Minh Thang     9.5       
GCH16573  Do Duy Tung         6.5       
GCH16603  Nguyen Thanh Thang  8.0       
GCH22000  Nguyen Minh Tuan    10        


In [27]:
codes, names, grades = np.loadtxt('gradebook.csv', delimiter=',', skiprows=1, 
                                  usecols=(2, 3, 4), dtype=str, unpack=True)
for i in range(len(codes)):
    if grades[i] == '':
        grades[i] = '0'
    if codes[i] == '':
        codes[i] = 'GCH22000'
    if float(grades[i]) > 10:
        grades[i] = '10'

# Save clean data into new file
np.savetxt('clean_gradebook.csv', np.column_stack((codes, names, grades)), delimiter=',', 
           fmt='%s', header='Code,Name,Grade')

print('Done!')


Done!


In [30]:
import csv

with open('gradebook.csv', 'r') as f:
    reader = csv.reader(f)
    with open('fail_students.csv', 'w') as fw:
        writer = csv.writer(fw)

        writer.writerow(next(reader))  # write header

        for row in reader:
            if row[4] == '':
                row[4] = '0'
            if float(row[4]) > 10:
                row[4] = '10'
            if row[2] == '':
                row[2] = 'GCH22000'
            if float(row[4]) < 6.5:
                writer.writerow(row)
print('Done!')

Done!


In [ ]:
# Clean pizza_data.csv
# Remove rows that have empty menus.amountMax, menus.amountMin
# Rows that have empty priceRangeMax, priceRangeMin -> set to 0
# For row that has more than one categories, keep just the 1st one
# Remove id column, url column
