In [2]:
products = ['pencil', 'eraser', 'ruler', 'pen', 'notebook']
prices = [1000, 500, 2000, 5000, 10000]
sold = [120, 1000, 80, 50, 30]

# Find product that has the highest sold
max_sold = prices[0] * sold[0]
i_max = 0
n = len(products)
for i in range(1, n): # ~ for (i = 1; i < n; i++)
    if prices[i] * sold[i] > max_sold:
        max_sold = prices[i] * sold[i]  # update max_sold
        i_max = i                       # update position of max_sold

print(f'{products[i_max]} has the highest sold: {max_sold}')
# Find product that has the lowest sold
min_sold = prices[0] * sold[0]
i_min = 0
for i in range(1, n):
    if prices[i] * sold[i] < min_sold:
        min_sold = prices[i] * sold[i]  # update min_sold
        i_min = i                       # update position of min_sold
print(f'{products[i_min]} has the lowest sold: {min_sold}')
# Find product that has the highest price
max_price = prices[0]
i_max = 0
for i in range(1, n):
    if prices[i] > max_price:
        max_price = prices[i]
        i_max = i
print(f'{products[i_max]} has the highest price: {max_price}')
# Find product that has the lowest price
min_price = prices[0]
i_min = 0
for i in range(1, n):
    if prices[i] < min_price:
        min_price = prices[i]
        i_min = i
print(f'{products[i_min]} has the lowest price: {min_price}')
# Find product that has sold the most

# Find product that has sold the least

eraser has the highest sold: 500000
pencil has the lowest sold: 120000
notebook has the highest price: 10000


In [3]:
products_sold = [['pencil', 1000, 120], 
                 ['eraser', 500, 1000], 
                 ['ruler', 2000, 80], 
                 ['pen', 5000, 50], 
                 ['notebook', 10000, 30]]

In [4]:
# Find product that has the highest sold
max_sold = products_sold[0][1] * products_sold[0][2]
i_max = 0
n = len(products_sold)
for i in range(1, n):
    if products_sold[i][1] * products_sold[i][2] > max_sold:
        max_sold = products_sold[i][1] * products_sold[i][2]
        i_max = i

print(f'{products_sold[i_max][0]} has the highest sold: {max_sold}')

eraser has the highest sold: 500000


In [6]:
# Find product that has max price
max_price = products_sold[0][1]
i_max = 0
for i in range(1, n):
    if products_sold[i][1] > max_price:
        max_price = products_sold[i][1]
        i_max = i
print(f'{products_sold[i_max][0]} has the highest price: {max_price}')
# Find produc that hals sold the least
min_sold = products_sold[0][2]
i_min = 0
for i in range(1, n):
    if products_sold[i][2] < min_sold:
        min_sold = products_sold[i][2]
        i_min = i
print(f'{products_sold[i_min][0]} has sold the least: {min_sold}')

notebook has the highest price: 10000
notebook has the lowest sold: 30


In [7]:
import random as rd
numbers = [[1, 2, 3, 4, 5], 
            [6, 7, 8, 9, 10], 
            [11, 12, 13, 14, 15], 
            [16, 17, 18, 19, 20], 
            [21, 22, 23, 24, 25]]

In [10]:
# Get 3 middle rows in as many ways as you can
# Method 1
middle = numbers[1:4]
print(middle)
# Method 2
print(numbers[1:-1])
# Method 3
print(numbers[-4:4])
# Method 4
print(numbers[-4:-1])

[[6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
[[6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
[[6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
[[6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]


In [13]:
# Get 2 last rows in as many ways as you can
print(numbers[3:])
print(numbers[-2:])
print(numbers[-2:5])
print(numbers[3:5])

[[16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]
[[16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]
[[16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]
[[16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]


In [17]:
n = int(input('Enter n: '))
print(f'Max of row {n}: {max(numbers[n])}')
print(f'Min of row {n}: {min(numbers[n])}')
print(f'Sum of row {n}: {sum(numbers[n])}')

Max of row 3: 20
Min of row 3: 16
Sum of row 3: 90


In [ ]:
import numpy as np
numbers = np.array([1, 2, 3, 4, 5])
print(numbers, type(numbers))

In [ ]:
a = [1, 2.5, 'hello', True]
b = np.array(a)
print(a, type(a))
print(b, type(b))

In [25]:
a = list(range(1, 11))
print(a)
b = np.arange(1, 11)
print(b)
# Full syntax arange: np.arange(start, stop, step)
print(np.arange(10))
print(np.arange(1, 20, 2))
print(np.arange(0, 20, 2))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]
[ 0  2  4  6  8 10 12 14 16 18]


In [31]:
# Function linspace: np.linspace(start, stop, num, endpoint)
print(np.linspace(1, 10, 10, dtype=int))
print(np.linspace(0, 10, 10, endpoint=False, dtype=int))
print(np.linspace(1, 19, 10, dtype=int))
print(np.linspace(0, 18, 10, dtype=int))

[ 1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]
[ 0  2  4  6  8 10 12 14 16 18]


In [34]:
print(np.arange(0, 10, 0.5))
print(np.linspace(0, 10, 20, endpoint=False))

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [38]:
# function logsapce: np.logspace(start, stop, num, endpoint, base)
a = np.linspace(1, 10, 10, endpoint=True, dtype=int)
b = 2**a
print(a)
print(b)
print(np.logspace(1, 10, 10, endpoint=True, base=2, dtype=int))

[ 1  2  3  4  5  6  7  8  9 10]
[   2    4    8   16   32   64  128  256  512 1024]
[   2    4    8   16   32   64  128  256  512 1024]


In [40]:
# Generate following numbers using logsapce
# 1 3 9 27 81 243
print(np.logspace(0, 5, 6, base=3, endpoint=True, dtype=int))
# 10 100 1000 10000 100000 1000000
print(np.logspace(1, 6, 6, endpoint=True, dtype=int))

[  1   3   9  27  81 243]
[     10     100    1000   10000  100000 1000000]


In [44]:
zeros = np.zeros(10,dtype=int)
ones = np.ones(10, dtype=int)
print(zeros)
print(ones)
print(ones * 2)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[2 2 2 2 2 2 2 2 2 2]


In [45]:
# Array operators: +, -, *, /, //, %, **
a = np.array([1, 2, 3, 4, 5])
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
print(a // 2)
print(a % 2)
print(a ** 2)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[0 1 1 2 2]
[1 0 1 0 1]
[ 1  4  9 16 25]


In [48]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a ** b)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[0 0 0 0 0]
[1 2 3 4 5]
[      1     128    6561  262144 9765625]


In [54]:
# generate 10 random numbers in range [0, 99]
numbers = np.random.randint(0, 100, 10)
print(numbers)
b = numbers % 2
print(b)
c = b == 0
print(c)
evens = numbers[c] # boolean indexing

[29 63 19  1 22 78 33 98 98 68]
[1 1 1 1 0 0 1 0 0 0]
[False False False False  True  True False  True  True  True]


In [56]:
print(evens)
odds = numbers[numbers % 2 == 1]
print(odds)

[22 78 98 98 68]
[29 63 19  1 33]


In [57]:
numbers = np.random.randint(-99, 100, 20)
# Find all positive numbers
print(numbers[numbers > 0])
# Find all negative numbers
print(numbers[numbers < 0])

[36 76  2 19 76 67]
[-69 -19 -75  -4 -59 -46 -19 -63  -3 -22  -3 -41 -77 -64]


In [58]:
numbers[numbers < 0] = 0
print(numbers)

[ 0  0  0  0 36  0  0  0 76  0  2  0 19 76  0  0 67  0  0  0]


In [62]:
names = np.array(['Barrack Obama', 'Donald Trump', '', 'Zoe Biden', 'Hillary Clinton'])
ages = np.array([59, 74, 78, -10, 272])
names[names == ''] = 'John Doe'
ages[ages < 0] = 0
ages[ages > 150] = 150

print(names)
print(ages)

['Barrack Obama' 'Donald Trump' 'John Doe' 'Zoe Biden' 'Hillary Clinton']
[ 59  74  78   0 150]


In [64]:
print(f'Min age = {min(ages)}')
print(f'Max age = {max(ages)}')
print(f'Longest name: {max(names, key=len)}')
print(f'Shortest name: {min(names, key=len)}')

Min age = 0
Max age = 150
Longest name: Hillary Clinton
Shortest name: John Doe
