In [2]:
import numpy as np
y = np.array([0., 1.3, 5. , 10.9, 18.9, 28.7, 40.]) 
t = np.array([0., 0.49, 1. , 1.5 , 2.08, 2.55, 3.2]) 
v = np.zeros(7)

for i in range(1,7):
    v[i] = (y[i] - y[i-1])/(t[i] - t[i-1])

print(v)

[ 0.          2.65306122  7.25490196 11.8        13.79310345 20.85106383
 17.38461538]


In [3]:
v[1:] = (y[1:] - y[:-1])/(t[1:] - t[:-1])
print(v)

[ 0.          2.65306122  7.25490196 11.8        13.79310345 20.85106383
 17.38461538]


In [5]:
# 2D arrays
a = np.array([1, 2, 3, 4, 5, 6])
print(a, a.shape)
b = np.reshape(a, (2, 3)) # Convert 1D array to 2D array 2x3
print(b, b.shape)

[1 2 3 4 5 6] (6,)
[[1 2 3]
 [4 5 6]] (2, 3)


In [10]:
a = np.zeros((2, 3), dtype=int)
print(a)
a = np.linspace(0, 1, 6) # Return 6 evenly spaced numbers over the interval [0, 1]
b = np.reshape(a, (2, 3))
print(b)

[[0 0 0]
 [0 0 0]]
[[0.  0.2 0.4]
 [0.6 0.8 1. ]]


In [11]:
a = np.random.randint(10, 100, (4, 4))
print(a)

[[62 77 68 34]
 [35 47 55 40]
 [84 37 95 13]
 [40 68 54 19]]


In [16]:
print(a[1][2], a[1, 2])
print(a[1:3, :])
print(a[:2, 1:3])

55 55
[[35 47 55 40]
 [84 37 95 13]]
[[77 68]
 [47 55]]


In [17]:
a = np.random.randint(1, 1000, (6, 6))
print(a)

[[321 252 488  17 996 499]
 [632 126 900 515 894  68]
 [730 876 735 222 912  28]
 [804 697 117 449  66 259]
 [886 298 808 832 584 965]
 [449 106 771 339 477 341]]


In [18]:
a[0] = 0
print(a)

[[  0   0   0   0   0   0]
 [632 126 900 515 894  68]
 [730 876 735 222 912  28]
 [804 697 117 449  66 259]
 [886 298 808 832 584 965]
 [449 106 771 339 477 341]]


In [19]:
a[2:4, 3:5] = 0
print(a)

[[  0   0   0   0   0   0]
 [632 126 900 515 894  68]
 [730 876 735   0   0  28]
 [804 697 117   0   0 259]
 [886 298 808 832 584 965]
 [449 106 771 339 477 341]]


In [20]:
# Create an 8 × 8 array with ones on all the edges and zeros everywhere else. 
a = np.ones((8, 8), dtype=int)
a[1:-1, 1:-1] = 0
print(a)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


In [24]:
# Create an 8 × 8 array of integers with a checkerboard pattern of ones and zeros. 
a = np.ones((8, 8), dtype=int)
a[::2, ::2] = 0
a[1::2, 1::2] = 0
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [28]:
a = np.random.randint(10, 100, (8, 8))
print(a)
a[a % 3 != 0] *= -1
print(a)

[[58 35 44 24 41 86 86 48]
 [77 71 56 79 47 71 44 22]
 [88 50 66 62 21 15 19 74]
 [71 29 77 62 90 97 35 70]
 [21 44 29 75 58 77 71 61]
 [84 13 19 36 87 70 35 72]
 [61 60 50 50 20 76 47 59]
 [33 70 66 39 16 55 19 94]]
[[-58 -35 -44  24 -41 -86 -86  48]
 [-77 -71 -56 -79 -47 -71 -44 -22]
 [-88 -50  66 -62  21  15 -19 -74]
 [-71 -29 -77 -62  90 -97 -35 -70]
 [ 21 -44 -29  75 -58 -77 -71 -61]
 [ 84 -13 -19  36  87 -70 -35  72]
 [-61  60 -50 -50 -20 -76 -47 -59]
 [ 33 -70  66  39 -16 -55 -19 -94]]


In [29]:
# Split the matrix above into 4 submatrices 4x4
b = a[4:, :4]
print(b)

[[ 21 -44 -29  75]
 [ 84 -13 -19  36]
 [-61  60 -50 -50]
 [ 33 -70  66  39]]


In [34]:
print(b.size, b.shape, np.mean(b), np.std(b))

16 (4, 4) 4.875 50.94835007142037
