In [2]:
import numpy as np
y = np.array([0., 1.3, 5. , 10.9, 18.9, 28.7, 40.]) 
t = np.array([0., 0.49, 1. , 1.5 , 2.08, 2.55, 3.2]) 
v = np.zeros(7)

for i in range(1,7):
    v[i] = (y[i] - y[i-1])/(t[i] - t[i-1])

print(v)

[ 0.          2.65306122  7.25490196 11.8        13.79310345 20.85106383
 17.38461538]


In [3]:
v[1:] = (y[1:] - y[:-1])/(t[1:] - t[:-1])
print(v)

[ 0.          2.65306122  7.25490196 11.8        13.79310345 20.85106383
 17.38461538]


In [5]:
# 2D arrays
a = np.array([1, 2, 3, 4, 5, 6])
print(a, a.shape)
b = np.reshape(a, (2, 3)) # Convert 1D array to 2D array 2x3
print(b, b.shape)

[1 2 3 4 5 6] (6,)
[[1 2 3]
 [4 5 6]] (2, 3)
